package templates

const InitializeTemplate = `// GENERATED CODE, DO NOT EDIT THIS FILE
package {{.MigrationType}}

import (
	{{if .IsMongo}}nosqlConnection "github.com/paulusrobin/leaf-utilities/database/nosql/nosql"{{else}}sqlConnection "github.com/paulusrobin/leaf-utilities/database/sql/sql"{{end}}
	"github.com/paulusrobin/leaf-utilities/leafMigration/helper/migration"
	leafLogger "github.com/paulusrobin/leaf-utilities/logger/logger"
)

func InitializeMigrations({{if .IsMongo}}conn nosqlConnection.Mongo{{else}}conn sqlConnection.ORM{{end}}, log leafLogger.Logger) []migration.Migration {
	var migrations = make([]migration.Migration, 0)
	{{range $version := .Versions}}migrations = append(migrations, Migration_{{$version}}(conn, log))
	{{ end }}return migrations
}
{{$IsMongo := .IsMongo}}{{range $version := .Versions}}
func Migration_{{$version}}({{if $IsMongo}}conn nosqlConnection.Mongo{{else}}conn sqlConnection.ORM{{end}}, log leafLogger.Logger) migration.Migration {
	return &migration_{{$version}}{
		Log:  log,
		Conn: conn,
	}
}
{{end}}
`
